### ISSUE TITLE
Embargo date resolution is once a day: update UI and docs correspondigly

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1118]
The embargo date verification happens every day at 00:02.

**Comment by nharraud** [comment]
If the embargo is checked once a day we should not accept dates with hour:minutes:seconds as people would expect this precise time to be used. This require to modify some code.

**Comment by nharraud** [comment]
In order to decide which is the best choice, check embargo once a day or more often, some stress test needs to be done.
Scenario: Test the worst case scenario, i.e. big B2Share instance on new years eve. Create a few million records. Add a few tens of thousand records which have their embargo date expiring at midnight. (This is an hypothetic scenario, it is not coming from user requests)

**Comment by emanueldima** [comment]
solved by https://github.com/EUDAT-B2SHARE/b2share/pull/1129
