### ISSUE TITLE
PIDs do not point to data objects

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#593]
The PIDs in B2SHARE are resolved to the landing pages in the repository. 
To have a consistent PID handling in the B2 services it would be good to let them point directly to the data objects (uploaded files) as it is the case in B2SFAE and B2STAGE. This would, I assume also, make the integration between services simpler.
If several files (data collections) are uploaded it is an open question how to generate the PID and what to attach it to. But this relates to an earlier issue about data collection up and download --> #404

**Comment by emanueldima** [comment]
Following the WP5 discussions, we decided that each file will have its own PID, which would be different than the PIDs of the records. It's still unclear how to distinguish between the file metadata and the file content; the PID could point by default to the data content, but when used with a PID fragment (e.g. `1234/343-23-4@metadata`) the service could resolve the PID to the file metadata.

**Comment by cjhak** [comment]
@emanueldima, what exactly is meant by "file metadata" here? Is it the metadata stored in the PID-record for the file?

**Comment by emanueldima** [comment]
The file metadata, in my current model, is the file name, size, checksum and creation/modification dates. Some of this metadata goes into the PID record (the checksum), but in general the full file metadata must be provided by b2share.

**Comment by cjhak** [comment]
The EUDAT Technical Committee decided at the February 2016 meeting that data objects (files) should have PIDs. The PID for a data object (file) should resolve to the file content (the actual data).

A data object can also have descriptive (i.e. user level) metadata associated with it. This is called a metadata object. Metadata objects can be uploaded by end users (as files), or they can be extracted from the data object (e.g. HDF-5 files), or metadata can be manually entered and linked to the data object (file). Metadata objects should also have PIDs.

A data object together with its metadata object is called a Digital Object. (Note that collections of Digital Objects also are Digital Objects and should have their own metadata and PIDs, but this will be described in some other ticket). The data object PID (the PID resolving to the actual file) is also the PID for the Digital Object.

For Digital Objects containing singular data objects (i.e. not collections) should the PIDs resolve to the data object (i.e. the file content) but use PID fragments to resolve to the metadata in a similar manner as described earlier in this ticket (e.g 1234/343-23-4@metadata).  Content negotiation should then be used to resolve to the landing page for the Digital Object if a html page is requested.

The details of the resolving mechanism remains at this point to be worked out by the B2HANDLE team.

**Comment by nharraud** [comment]
Are there any use cases showing how the PIDs will be used? By use case I mean full scenario with specific needs provided by users and how the tools (B2Share, B2Safe, etc…) should used to fulfil them.

Example of use cases:
- A researcher wants to reference a file in his paper. What PID is he supposed to use? The metadata one? The one enabling to download the file content? If it is the second one, how is the reader of the paper supposed to know that he has to modify the EPIC PID to access the metadata?
- A client uses the REST API to list all the files of a given record. Should we list internal links or EPIC PIDs? The second option would mean that the PID server is used during B2Share REST requests for each file access. I don't think that this would scale.

Other questions:
- Can a file change once it has a PID? Can its metadata change?
- You said that the metadata can extracted be extracted from the file. Is it done once and for all when the file is uploaded or is it done each time somebody asks for it?
- You said that the metadata can be linked to a file. Can it be linked after the file has its PID assigned? Can it be linked after the metadata has its PID assigned?
- Do file metadata contain PID of the file content? Otherwise clients will have to hardcode the transformation of PIDs.
- What are collections of DigitalObject? Are those Records?

A few ideas I submit to you all are:

1/ Whenever B2Share sends EPIC PIDs through the REST API, it should give both the PID for metadata (e.g 1234/343-23-4@metadata) and the one for the file. That way the clients don't have to hard code the transformation from one to the other. The other possibility is to list only the metadata and having the metadata contain the PID pointing to the file content.

2/ B2Share should also list internal links to the data and not only PIDs, otherwise the PID server will go down very fast.

**Comment by emanueldima** [comment]
this should be fixed with https://github.com/EUDAT-B2SHARE/b2share/pull/1087
