### ISSUE TITLE
Faceted search gone

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#657]
The search facets we used to display on the search result page are gone:

![image](https://cloud.githubusercontent.com/assets/6217533/7725381/671192a6-fefa-11e4-8c0e-e9c6f6c03468.png)

**Comment by tiborsimko** [comment]
This may happen when there are JS errors on the page; please check the console:

- TypeError: n is undefined search.js:2
- TypeError: searchForm is not a function

**Comment by cjhak** [comment]
Increasing priority of this issue.

**Comment by emanueldima** [comment]
Looks like the problem is not related to the JS errors, but to a change in Invenio from version 1 to version 2, namely the facets table. The search facets are now no longer identical with the declared collections (which in B2SHARE are the communities), but must be explicitly declared in the database (in the facet_collection table). To create the necessary facets the superadmin can use the UI  at /admin/facetcollection/

@llehtine: Please go to /admin/facetcollection and add one facet for each B2SHARE community, both on the test server and the production. Or you could do it on the test server first and then copy the facet_collection table to production.

**Comment by llehtine** [comment]
This is now done on test/prod/training. Seems to be working now.
