### ISSUE TITLE
Moving data directory via CFG_WEBSUBMIT_STORAGEDIR

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#740]
I wanted to change the data directory of Invenio, I've found the `b2share/invenio/base/config.py` file, and have defined `CFG_WEBSUBMIT_STORAGEDIR ` in my `invenio.cfg`. This works, and the old uploaded files are still retrievable via the web-interface.

Do my changes have more implication to the working of Invenio itself?

**Comment by nharraud** [comment]
I don’t think we are using the websubmit module in B2Share (http://demo.invenio-software.org/help/admin/websubmit-admin-guide) as we have our own submission steps. Also we are downloading user files in B2Submit right?

I just asked Jiri and he told me that there isn’t “one” variable which tells where invenio can put all its data. It has to be overridden with multiple variables. Invenio has been designed so that by default everything is in the virtual environment you setup.

I’m searching right now for the list of variables.

-- 
Nicolas Harraudeau
IT engineer for EUDAT B2SHARE

On 12 Aug 2015 at 13:18:21, Dennis Blommesteijn (notifications@github.com) wrote:

I wanted to change the data directory of Invenio, I've found the b2share/invenio/base/config.py file, and have defined CFG_WEBSUBMIT_STORAGEDIR in my invenio.cfg. This works, and the old uploaded files are still retrievable via the web-interface.

Do my changes have more implication to the working of Invenio itself?

**Comment by nharraud** [comment]
The variables are:
CFG_BATCHUPLOADER_DAEMON_DIR
CFG_BIBDOCFILE_FILEDIR
CFG_BIBENCODE_DAEMON_DIR_NEWJOBS
CFG_BIBENCODE_DAEMON_DIR_OLDJOBS
CFG_BIBENCODE_TARGET_DIRECTORY
CFG_BINDIR
CFG_CACHEDIR
CFG_ETCDIR
CFG_LOCALEDIR
CFG_LOGDIR
CFG_PYLIBDIR
CFG_RUNDIR
CFG_TMPDIR
CFG_TMPSHAREDDIR
CFG_BIBEDIT_CACHEDIR
CFG_WEBBASKET_DIRECTORY_BOX_NUMBER_OF_COLUMNS
CFG_WEBDIR
CFG_WEBSUBMIT_BIBCONVERTCONFIGDIR
CFG_WEBSUBMIT_COUNTERSDIR
CFG_WEBSUBMIT_STORAGEDIR

You can find this list in invenio/ext/legacy/__init__.py and in invenio/base/config.py

I am not sure that we use all those directories but we might as well override them all.

CFG_PREFIX, which you can see in invenio/base/config.py, is deprecated.

-- 
Nicolas Harraudeau
IT engineer for EUDAT B2SHARE

On 12 Aug 2015 at 13:54:34, Nicolas Harraudeau (nicolas.harraudeau@cern.ch) wrote:

I don’t think we are using the websubmit module in B2Share (http://demo.invenio-software.org/help/admin/websubmit-admin-guide) as we have our own submission steps. Also we are downloading user files in B2Submit right?

I just asked Jiri and he told me that there isn’t “one” variable which tells where invenio can put all its data. It has to be overridden with multiple variables. Invenio has been designed so that by default everything is in the virtual environment you setup.

I’m searching right now for the list of variables.

-- 
Nicolas Harraudeau
IT engineer for EUDAT B2SHARE

On 12 Aug 2015 at 13:18:21, Dennis Blommesteijn (notifications@github.com) wrote:

I wanted to change the data directory of Invenio, I've found the b2share/invenio/base/config.py file, and have defined CFG_WEBSUBMIT_STORAGEDIR in my invenio.cfg. This works, and the old uploaded files are still retrievable via the web-interface.

Do my changes have more implication to the working of Invenio itself?

**Comment by nharraud** [comment]
The legacy modules's variables are:
```
CFG_BATCHUPLOADER_DAEMON_DIR
CFG_BIBDOCFILE_FILEDIR
CFG_BIBENCODE_DAEMON_DIR_NEWJOBS
CFG_BIBENCODE_DAEMON_DIR_OLDJOBS
CFG_BIBENCODE_TARGET_DIRECTORY
CFG_BINDIR
CFG_CACHEDIR
CFG_ETCDIR
CFG_LOCALEDIR
CFG_LOGDIR
CFG_PYLIBDIR
CFG_RUNDIR
CFG_TMPDIR
CFG_TMPSHAREDDIR
CFG_BIBEDIT_CACHEDIR
CFG_WEBBASKET_DIRECTORY_BOX_NUMBER_OF_COLUMNS
CFG_WEBDIR
CFG_WEBSUBMIT_BIBCONVERTCONFIGDIR
CFG_WEBSUBMIT_COUNTERSDIR
CFG_WEBSUBMIT_STORAGEDIR
```
You can find this list in invenio/ext/legacy/__init__.py and in invenio/base/config.py

I am not sure that we use all those directories but we might as well override them all.

CFG_PREFIX, which you can see in invenio/base/config.py, is deprecated.

However I don't have the list for the non-legacy modules.

**Comment by dblommesteijn** [comment]
Ok, but `CFG_WEBSUBMIT_STORAGEDIR` does seem to be the correct variable.
