### ISSUE TITLE
Implement a "b2share.eudat.eu/collection/XXX" re-direct

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#749]
RDA is planning to use b2share.eudat.eu/collection/RDA as a permanent link to list all RDA material. The term 'collection' follows the semantics of Invenio, but the term may be used differently in EUDAT terminology. Should we take the chance to change this  while we can, and if so to what? Perhaps b2share.eudat.eu/community/XXX (where XXX is a community name)? 

In that case we need to change it with the 1.6 release.

**Comment by nharraud** [comment]
"collections" are indeed an implementation detail and Invenio use them for other purposes too. Thus it is a good idea to change it to "community". However doing this change the day of the code-freeze might add new bugs like links pointing to wrong pages. We don't have enough tests to check this.

Either way the naming is already strange in B2Share. We use `domain` on submission page and in the code, `collection` in the URI and `community` for buttons (which has recently been removed).

We can change it in the URI but we still have to accept the old URI and redirect to the new one so that people's bookmarks still work for at least a few weeks/months. I think we can do this later.

**Comment by cjhak** [comment]
I agree that a redirect would be the best solution. Allowing two URI would also be ok for now. I'm worried that RDA will start using the URI as a link to an official RDA document listing. They don't mind if we make a change now, but later can be difficult in that case.

**Comment by cjhak** [comment]
We should perhaps use plural here in analogy with the API, hence:

b2share.eudat.eu/communities/XXX

**Comment by emanueldima** [comment]
too old to take into account now
