### ISSUE TITLE
Track number of views and number of downloads per file and per record

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#827]

**Comment by thijscobben** [comment]
Maybe I could take it

**Comment by nharraud** [comment]
@lnielsen has started an invenio-stat module. It is not contributed back to invenio yet but only because it needs some code split. Maybe we could use it once it is there, and contribute to it if some features are missing.

Another note: While I was at the Open Repositories 2016 conference there was a talk about [COUNTER](https://www.projectcounter.org/) which is a standard in development for uniform download counting statistics across digital libraries.

**Comment by nharraud** [comment]
UI PR from Sarah: #1520
Invenio-stats will be integrated to provide the data and REST API.
First step is to simply have the number of downloads per file for each file bucket.

**Comment by emanueldima** [comment]
downloads per file tracked in v2.1.0
